### ISSUE TITLE
metadata mismatch error when running ng serve after sucessful install and intergration

### ISSUE THREAD

**Issue by Christopher-Jakob** [NileshPatel17/ng-multiselect-dropdown#15]
ERROR in Error: Metadata version mismatch for module /home/rickus/Documents/softwareProjects/211hospitality/suitsandtables/frontend/suitsandtables/node_modules/ng-multiselect-dropdown/ng-multiselect-dropdown.d.ts, found version 4, expected 3

**Comment by NileshPatel17** [comment]
Please share more info.
Thanks!

**Comment by catullum** [comment]
ERROR in Error: Metadata version mismatch for module C:/programming/Angular/Angular/Filter/src/portal/node_modules/ng-multiselect-dropdown/ng-multiselect-dropdown.d.ts, found version 4, expected 3, resolving symbol AppModule in C:/programming/Angular/Angular/Filter/src/portal/src/app/app.module.ts, resolving symbol AppModule in C:/programming/Angular/Angular/Filter/src/portal/src/app/app.module.ts, resolving symbol AppModule in C:/programming/Angular/Angular/Filter/src/portal/src/app/app.module.ts
    at syntaxError (C:\programming\Angular\Angular\Filter\src\portal\node_modules\@angular\compiler\bundles\compiler.umd.js:1729:34)
    at simplifyInContext (C:\programming\Angular\Angular\Filter\src\portal\node_modules\@angular\compiler\bundles\compiler.umd.js:24979:23)
    at StaticReflector.simplify (C:\programming\Angular\Angular\Filter\src\portal\node_modules\@angular\compiler\bundles\compiler.umd.js:24991:13)
    at StaticReflector.annotations (C:\programming\Angular\Angular\Filter\src\portal\node_modules\@angular\compiler\bundles\compiler.umd.js:24418:41)
    at _getNgModuleMetadata (C:\programming\Angular\Angular\Filter\src\portal\node_modules\@angular\compiler-cli\src\ngtools_impl.js:138:31)
    at _extractLazyRoutesFromStaticModule (C:\programming\Angular\Angular\Filter\src\portal\node_modules\@angular\compiler-cli\src\ngtools_impl.js:109:26)
    at Object.listLazyRoutesOfModule (C:\programming\Angular\Angular\Filter\src\portal\node_modules\@angular\compiler-cli\src\ngtools_impl.js:53:22)
    at Function.NgTools_InternalApi_NG_2.listLazyRoutes (C:\programming\Angular\Angular\Filter\src\portal\node_modules\@angular\compiler-cli\src\ngtools_api.js:91:39)
    at AotPlugin._getLazyRoutesFromNgtools (C:\programming\Angular\Angular\Filter\src\portal\node_modules\@ngtools\webpack\src\plugin.js:240:66)
    at _donePromise.Promise.resolve.then.then.then.then.then (C:\programming\Angular\Angular\Filter\src\portal\node_modules\@ngtools\webpack\src\plugin.js:493:24)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)

    _                      _                 ____ _     ___
   / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
  / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
 / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
/_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
               |___/

Angular CLI: 1.7.4
Node: 8.9.1
OS: win32 x64
Angular: 4.4.7
... animations, common, compiler, compiler-cli, core, forms
... http, platform-browser, platform-browser-dynamic
... platform-server, router, tsc-wrapped

@angular/cli: 1.7.4
@angular-devkit/build-optimizer: 0.3.2
@angular-devkit/core: 0.3.2
@angular-devkit/schematics: 0.3.2
@ngtools/json-schema: 1.2.0
@ngtools/webpack: 1.10.2
@schematics/angular: 0.3.2
@schematics/package-update: 0.3.2
typescript: 2.3.4
webpack: 3.11.0

**Comment by collaorodrigo7** [comment]
any idea why could this happen? I am having the same issue. Is it related to angular version?

**Comment by dsandeepchary** [comment]
You can avoid the error by degrading to the `0.1.4` version, but there is no search feature if you use it.
@Christopher-Jakob  @catullum  @collaorodrigo7

**Comment by collaorodrigo7** [comment]
thank you!, that was exactly what I was planning on posting. I did that and works. thanks @dsandeepchary

**Comment by dsandeepchary** [comment]
@NileshPatel17 Is there a fix for this yet?

**Comment by NileshPatel17** [comment]
Not sure its an issue. Please try with latest version, and let me know if you still experience this issue.

**Comment by Wrecklaimer** [comment]
It is definitely still an issue with latest (0.1.8). I am getting this error when running tests (`ng test`) for my Angular 4 app.

Is this only compatible with Angular 5+?

**Comment by prafful-garg** [comment]
This is the issue with version 0,.0.6, 0.,1.7 and 0.1.8 all, please fix this

**Comment by Wrecklaimer** [comment]
@NileshPatel17 As I said before, I am having the issue when using **Angular 4.x**. It seems like you have it building for 5+, hence why you don't have any issues in your example (using 6.x). Also, the error only occurs for me when running unit tests.

**Comment by Gabb1995** [comment]
Having the same issue.

**Comment by pavitrag123** [comment]
I'm also facing same issue while using package for angular 4 application. Can you please provide alternative  compatible with angular 4? Tried npm update, still same issue

**Comment by gitlantz** [comment]
I have the same issue.  I'm at 0.1.4.  I need to go to 0.2.1 to bypass this (https://github.com/NileshPatel17/ng-multiselect-dropdown/issues/67) issue, but can't.

**Comment by pavitrag123** [comment]
I used angular4-multiselect instead
