### ISSUE TITLE
error in build project using TFS/VSTS

### ISSUE THREAD

**Issue by yousefchtourou** [NileshPatel17/ng-multiselect-dropdown#180]
some error in build project using TFS Server

```
2019-10-19T12:49:26.5596326Z [0m[1m[31mERROR in ./node_modules/ng-multiselect-dropdown/fesm5/ng-multiselect-dropdown.js[39m[22m[0m
2019-10-19T12:49:26.5596326Z [0m[1m[31mModule build failed: TypeError: Cannot read property 'kind' of undefined[39m[22m[0m
2019-10-19T12:49:26.5596326Z [0m[1m[31m    at isAngularDecoratorMetadataExpression (D:\agent\_work\97\s\node_modules\@angular-devkit\build-optimizer\src\transforms\scrub-file.js:242:35)[39m[22m[0m
2019-10-19T12:49:26.5596326Z [0m[1m[31m    at checkNodeForDecorators (D:\agent\_work\97\s\node_modules\@angular-devkit\build-optimizer\src\transforms\scrub-file.js:67:21)[39m[22m[0m
2019-10-19T12:49:26.5596326Z [0m[1m[31m    at visitNodes (D:\agent\_work\97\s\node_modules\@angular-devkit\build-optimizer\node_modules\typescript\lib\typescript.js:12699:30)[39m[22m[0m
2019-10-19T12:49:26.5596326Z [0m[1m[31m    at Object.forEachChild (D:\agent\_work\97\s\node_modules\@angular-devkit\build-optimizer\node_modules\typescript\lib\typescript.js:12875:24)[39m[22m[0m
2019-10-19T12:49:26.5596326Z [0m[1m[31m    at checkNodeForDecorators (D:\agent\_work\97\s\node_modules\@angular-devkit\build-optimizer\src\transforms\scrub-file.js:58:31)[39m[22m[0m
2019-10-19T12:49:26.5596326Z [0m[1m[31m    at visitNode (D:\agent\_work\97\s\node_modules\@angular-devkit\build-optimizer\node_modules\typescript\lib\typescript.js:12690:24)[39m[22m[0m
2019-10-19T12:49:26.5596326Z [0m[1m[31m    at Object.forEachChild (D:\agent\_work\97\s\node_modules\@angular-devkit\build-optimizer\node_modules\typescript\lib\typescript.js:12782:21)[39m[22m[0m
2019-10-19T12:49:26.5596326Z [0m[1m[31m    at checkNodeForDecorators (D:\agent\_work\97\s\node_modules\@angular-devkit\build-optimizer\src\transforms\scrub-file.js:58:31)[39m[22m[0m
2019-10-19T12:49:26.5596326Z [0m[1m[31m    at visitNode (D:\agent\_work\97\s\node_modules\@angular-devkit\build-optimizer\node_modules\typescript\lib\typescript.js:12690:24)[39m[22m[0m
2019-10-19T12:49:26.5596326Z [0m[1m[31m    at Object.forEachChild (D:\agent\_work\97\s\node_modules\@angular-devkit\build-optimizer\node_modules\typescript\lib\typescript.js:12828:24)[39m[22m[0m
2019-10-19T12:49:26.5596326Z [0m[1m[31m    at checkNodeForDecorators (D:\agent\_work\97\s\node_modules\@angular-devkit\build-optimizer\src\transforms\scrub-file.js:58:31)[39m[22m[0m
2019-10-19T12:49:26.5596326Z [0m[1m[31m    at visitNode (D:\agent\_work\97\s\node_modules\@angular-devkit\build-optimizer\node_modules\typescript\lib\typescript.js:12690:24)[39m[22m[0m
2019-10-19T12:49:26.5596326Z [0m[1m[31m    at Object.forEachChild (D:\agent\_work\97\s\node_modules\@angular-devkit\build-optimizer\node_modules\typescript\lib\typescript.js:12838:24)[39m[22m[0m
2019-10-19T12:49:26.5596326Z [0m[1m[31m    at checkNodeForDecorators (D:\agent\_work\97\s\node_modules\@angular-devkit\build-optimizer\src\transforms\scrub-file.js:58:31)[39m[22m[0m
2019-10-19T12:49:26.5596326Z [0m[1m[31m    at visitNode (D:\agent\_work\97\s\node_modules\@angular-devkit\build-optimizer\node_modules\typescript\lib\typescript.js:12690:24)[39m[22m[0m
2019-10-19T12:49:26.5596326Z [0m[1m[31m    at Object.forEachChild (D:\agent\_work\97\s\node_modules\@angular-devkit\build-optimizer\node_modules\typescript\lib\typescript.js:12754:21)[39m[22m[0m
```

**Comment by yousefchtourou** [comment]
version ng-multiselect-dropdown = 0.2.3

**Comment by NileshPatel17** [comment]
Please refer #178 . Hope it helps.
