### ISSUE TITLE
NullInjectorError: No provider for ListFilterPipe!

### ISSUE THREAD

**Issue by contactipraju** [NileshPatel17/ng-multiselect-dropdown#301]
**Angular version**: ~10.2.1

**ng-multiselect-dropdown version**: ^0.3.0

**Description of issue**:
Getting the following run-time error in console, when implemented the sample from https://www.npmjs.com/package/ng-multiselect-dropdown

core.js:4442 ERROR NullInjectorError: R3InjectorError(AppModule)[ListFilterPipe -> ListFilterPipe -> ListFilterPipe]: 
  NullInjectorError: No provider for ListFilterPipe!
    at NullInjector.get (http://localhost:4200/vendor.js:41066:27)
    at R3Injector.get (http://localhost:4200/vendor.js:51185:33)
    at R3Injector.get (http://localhost:4200/vendor.js:51185:33)
    at R3Injector.get (http://localhost:4200/vendor.js:51185:33)
    at NgModuleRef$1.get (http://localhost:4200/vendor.js:64314:33)
    at Object.get (http://localhost:4200/vendor.js:64011:35)
    at getOrCreateInjectable (http://localhost:4200/vendor.js:44222:39)
    at Module.ɵɵdirectiveInject (http://localhost:4200/vendor.js:54715:12)
    at NodeInjectorFactory.MultiSelectComponent_Factory [as factory] (http://localhost:4200/modules-tplan-editor-tplan-editor-module.js:3462:174)
    at getNodeInjectable (http://localhost:4200/vendor.js:44327:44)

**Steps to reproduce**:
Just load a page with sample implementation

**Expected result**:
Dropdown should appear

**Actual result**:
Nothing is loaded and throwing a JS error

**Demo**: Please share sample code link using StackBlitz or codesandbox
Sample at: https://www.npmjs.com/package/ng-multiselect-dropdown

Any relevant code:
```

**Comment by MikeInSwitzerland** [comment]
Yup, I get exactly the same error, when I try and run their demo.

**Comment by hackermanmx** [comment]
I'm experiencing the exact same error in latest version, any updates, pls?

**Comment by subhasishdash** [comment]
Happens to me too .
I saw the issue when I load the ng-multiselectdropdown in a bootstrap modal when using NgbModal.open(Component)
On page load it works fine.

**Comment by hackermanmx** [comment]
> Happens to me too . I saw the issue when I load the ng-multiselectdropdown in a bootstrap modal when using NgbModal.open(Component) On page load it works fine.
> 
> If I keep NgMultiSelectDropDownModule.forRoot() in app.module.ts , it works fine



> Happens to me too . I saw the issue when I load the ng-multiselectdropdown in a bootstrap modal when using NgbModal.open(Component) On page load it works fine.
> 
> If I keep NgMultiSelectDropDownModule.forRoot() in app.module.ts , it works fine

This actually solved it, even though I had it referenced in a shared module, this fixed it. Thanks for sharing!

**Comment by itzmesurya** [comment]
> Happens to me too . I saw the issue when I load the ng-multiselectdropdown in a bootstrap modal when using NgbModal.open(Component) On page load it works fine.
> 
> If I keep NgMultiSelectDropDownModule.forRoot() in app.module.ts , it works fine

This fixed my issue
