### ISSUE TITLE
ng build --prod Error : 'kind' of undefined 

### ISSUE THREAD

**Issue by sagarbehal08** [NileshPatel17/ng-multiselect-dropdown#316]
On ng build --prod Error: 'kind' of undefined
ng-multiselect-dropdown:^1.0.0-beta.13,
need to use beta version: required ng-template for translate content in the dropdown

**Comment by brt-han-mai** [comment]
Same issue on version 0.3.4. Build production failed!

```bash
ERROR in ./node_modules/ng-multiselect-dropdown/fesm5/ng-multiselect-dropdown.js
Module build failed (from ./node_modules/@angular-devkit/build-optimizer/src/build-optimizer/webpack-loader.js):
TypeError: Cannot read property 'kind' of undefined
    at isAngularDecoratorMetadataExpression (C:\Users\han.mai\Desktop\work\my_project_name\node_modules\@angular-devkit\build-optimizer\src\transforms\scrub-file.js:242:35)
    at checkNodeForDecorators (C:\Users\han.mai\Desktop\work\my_project_name\node_modules\@angular-devkit\build-optimizer\src\transforms\scrub-file.js:67:21)
    at visitNodes (C:\Users\han.mai\Desktop\work\my_project_name\node_modules\typescript\lib\typescript.js:14809:30)
    at Object.forEachChild (C:\Users\han.mai\Desktop\work\my_project_name\node_modules\typescript\lib\typescript.js:15033:24)
    at checkNodeForDecorators (C:\Users\han.mai\Desktop\work\my_project_name\node_modules\@angular-devkit\build-optimizer\src\transforms\scrub-file.js:58:31)
    at visitNode (C:\Users\han.mai\Desktop\work\my_project_name\node_modules\typescript\lib\typescript.js:14800:24)
    at Object.forEachChild (C:\Users\han.mai\Desktop\work\my_project_name\node_modules\typescript\lib\typescript.js:14928:21)
    at checkNodeForDecorators (C:\Users\han.mai\Desktop\work\my_project_name\node_modules\@angular-devkit\build-optimizer\src\transforms\scrub-file.js:58:31)
    at visitNode (C:\Users\han.mai\Desktop\work\my_project_name\node_modules\typescript\lib\typescript.js:14800:24)
    at Object.forEachChild (C:\Users\han.mai\Desktop\work\my_project_name\node_modules\typescript\lib\typescript.js:14985:24)
    at checkNodeForDecorators (C:\Users\han.mai\Desktop\work\my_project_name\node_modules\@angular-devkit\build-optimizer\src\transforms\scrub-file.js:58:31)
    at visitNode (C:\Users\han.mai\Desktop\work\my_project_name\node_modules\typescript\lib\typescript.js:14800:24)
    at Object.forEachChild (C:\Users\han.mai\Desktop\work\my_project_name\node_modules\typescript\lib\typescript.js:14996:24)
    at checkNodeForDecorators (C:\Users\han.mai\Desktop\work\my_project_name\node_modules\@angular-devkit\build-optimizer\src\transforms\scrub-file.js:58:31)
    at visitNode (C:\Users\han.mai\Desktop\work\my_project_name\node_modules\typescript\lib\typescript.js:14800:24)
    at Object.forEachChild (C:\Users\han.mai\Desktop\work\my_project_name\node_modules\typescript\lib\typescript.js:14893:21)
```

**Comment by toastyghost** [comment]
Same for 0.3.7

Running build on Node 12 and Angular 7 if that makes a difference
