### ISSUE TITLE
Cannot read properties of undefined (reading 'idField')

### ISSUE THREAD

**Issue by RicardoRibeirorr** [NileshPatel17/ng-multiselect-dropdown#380]
#Error
core.js:6456 ERROR TypeError: Cannot read properties of undefined (reading 'idField')
    at MultiSelectComponent.deobjectify (ng-multiselect-dropdown.js:395:1)
    at ng-multiselect-dropdown.js:229:1
    at Array.map (<anonymous>)
    at set data [as data] (ng-multiselect-dropdown.js:229:1)
    at setInputsForProperty (core.js:10940:13)
    at elementPropertyInternal (core.js:9984:9)
    at ɵɵproperty (core.js:14764:9)
    at StepBeneficiosComponent_Template (step-beneficios.component.html:36:44)
    at executeTemplate (core.js:9579:9)
    at refreshView (core.js:9445:13)
    

#HTML
<ng-multiselect-dropdown
              name="country"
              [placeholder]="'Select City'"
              [settings]="dropdownSettings"
              [data]="countries"
            ></ng-multiselect-dropdown>

**Comment by RicardoRibeirorr** [comment]
SOLUTION:
Change the order of the properties, and put "settings" before "data" or every other that you may have problems with.
ex:
<ng-multiselect-dropdown
              [settings]="dropdownSettings"   //first
              [data]="countries"                       //second
></ng-multiselect-dropdown>


FIXING PROBLEM ON NEXT STAGES OF THE PACKAGE:
    deobjectify(item) {
        //FIX: Validate if "this._settings" is null before procede with the code.
        if (typeof item === "string" || typeof item === "number") {
            return new ListItem(item);
        }
        else {
            return new ListItem({
                id: item[this._settings.idField],
                text: item[this._settings.textField],
                tooltip: item[this._settings.tooltipField],
                isDisabled: item[this._settings.disabledField]
            });
        }
    }

**Comment by RicardoRibeirorr** [comment]
SOLUTION:
Change the order of the properties, and put "settings" before "data" or every other that you may have problems with.
ex:
<ng-multiselect-dropdown
[settings]="dropdownSettings" //first
[data]="countries" //second

FIXING PROBLEM ON NEXT STAGES OF THE PACKAGE:
deobjectify(item) {
//FIX: Validate if "this._settings" is null before procede with the code.
if (typeof item === "string" || typeof item === "number") {
return new ListItem(item);
}
else {
return new ListItem({
id: item[this._settings.idField],
text: item[this._settings.textField],
tooltip: item[this._settings.tooltipField],
isDisabled: item[this._settings.disabledField]
});
}
}
