### ISSUE TITLE
`angular.json` could not be found

### ISSUE THREAD

**Issue by tomsaleeba** [NileshPatel17/ng-multiselect-dropdown#48]
Environment:
```console
$ yarn --version
Yarn 1.7.0
```
```console
$ ng --version

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 6.0.8
Node: 9.11.1
OS: linux x64
Angular: 6.0.7
... core

Package                             Version
-------------------------------------------------------------
@angular-devkit/architect           0.6.8
@angular-devkit/core                0.6.8
@angular-devkit/schematics          0.6.8
@angular/animations                 5.2.9
@angular/cli                        6.0.8
@angular/common                     5.2.9
@angular/compiler                   5.2.9
@angular/compiler-cli               5.2.9
@angular/forms                      5.2.9
@angular/http                       5.2.9
@angular/language-service           5.2.9
@angular/platform-browser           5.2.9
@angular/platform-browser-dynamic   5.2.9
@angular/router                     5.2.9
@ngtools/json-schema                1.1.0
@schematics/angular                 0.6.8
@schematics/update                  0.6.8
ng-packagr                          2.4.5
rxjs                                5.5.11
typescript                          2.6.2
```

Steps:
 1. git clone 09fc01c597ce5b0dcca21d9f92f8f3f74ec3ad9e
 1. `yarn` *or* `npm i`

Expected:
Seeing as running installing deps also builds, I expect that it should all work.

Actual:
The build fails, see full log output for yarn:
```console
$ yarn
yarn install v1.7.0
info No lockfile found.
[1/4] Resolving packages...
warning angular-library-builder > gulp > vinyl-fs > graceful-fs@3.0.11: please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js
warning angular-library-builder > gulp > gulp-util@3.0.8: gulp-util is deprecated - replace it, following the guidelines at https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5
warning angular-library-builder > gulp-inline-ng2-template > gulp-util@3.0.8: gulp-util is deprecated - replace it, following the guidelines at https://medium.com/gulpjs/gul
p-util-ca3b1f9f9ac5
warning angular-library-builder > gulp > vinyl-fs > glob-stream > minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
warning angular-library-builder > gulp > vinyl-fs > glob-stream > glob > minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
warning angular-library-builder > gulp > vinyl-fs > glob-watcher > gaze > globule > minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
warning angular-library-builder > gulp > vinyl-fs > glob-watcher > gaze > globule > glob > minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS
 issue
warning angular-library-builder > gulp > vinyl-fs > glob-watcher > gaze > globule > glob > graceful-fs@1.2.3: please upgrade to graceful-fs 4 for compatibility with current 
and future versions of Node.js
warning karma-coverage-istanbul-reporter > istanbul-api > istanbul-lib-hook@1.2.1: 1.2.0 should have been a major version bump
[2/4] Fetching packages...
info fsevents@1.2.4: The platform "linux" is incompatible with this module.
info "fsevents@1.2.4" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
warning " > @angular/animations@5.2.9" has incorrect peer dependency "@angular/core@5.2.9".
warning " > @angular/common@5.2.9" has incorrect peer dependency "@angular/core@5.2.9".
warning " > @angular/core@6.0.7" has incorrect peer dependency "rxjs@^6.0.0".
warning " > @angular/forms@5.2.9" has incorrect peer dependency "@angular/core@5.2.9".
warning " > @angular/http@5.2.9" has incorrect peer dependency "@angular/core@5.2.9".
warning " > @angular/platform-browser@5.2.9" has incorrect peer dependency "@angular/core@5.2.9".
warning " > @angular/platform-browser-dynamic@5.2.9" has incorrect peer dependency "@angular/core@5.2.9".
warning " > @angular/router@5.2.9" has incorrect peer dependency "@angular/core@5.2.9".
warning " > angular2-markdown@1.6.0" has incorrect peer dependency "@angular/core@^2.4.0 || ^4.0.3".
warning " > angular2-markdown@1.6.0" has incorrect peer dependency "@angular/http@^2.4.0 || ^4.0.3".
warning " > codelyzer@3.0.1" has incorrect peer dependency "@angular/compiler@^2.3.1 || >=4.0.0-beta <5.0.0".
warning " > codelyzer@3.0.1" has incorrect peer dependency "@angular/core@^2.3.1 || >=4.0.0-beta <5.0.0".
warning " > ng-multiselect-dropdown@0.1.9" has incorrect peer dependency "@angular/common@^4.0.0 || ^6.0.0".
warning " > ng-packagr@2.4.5" has unmet peer dependency "tsickle@>=0.25.5".
warning " > ng-packagr@2.4.5" has unmet peer dependency "tslib@^1.7.1".
[4/4] Building fresh packages...
success Saved lockfile.
$ yarn build:prod
yarn run v1.7.0
$ ng build --prod --base-href https://nileshpatel17.github.io/ng-multiselect-dropdown/
Local workspace file ('angular.json') could not be found.
Error: Local workspace file ('angular.json') could not be found.
    at WorkspaceLoader._getProjectWorkspaceFilePath (/zeta/git/ng-multiselect-dropdown/node_modules/@angular/cli/models/workspace-loader.js:37:19)
    at WorkspaceLoader.loadWorkspace (/zeta/git/ng-multiselect-dropdown/node_modules/@angular/cli/models/workspace-loader.js:24:21)
    at BuildCommand._loadWorkspaceAndArchitect (/zeta/git/ng-multiselect-dropdown/node_modules/@angular/cli/models/architect-command.js:180:32)
    at BuildCommand.<anonymous> (/zeta/git/ng-multiselect-dropdown/node_modules/@angular/cli/models/architect-command.js:47:25)
    at Generator.next (<anonymous>)
    at /zeta/git/ng-multiselect-dropdown/node_modules/@angular/cli/models/architect-command.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (/zeta/git/ng-multiselect-dropdown/node_modules/@angular/cli/models/architect-command.js:3:12)
    at BuildCommand.initialize (/zeta/git/ng-multiselect-dropdown/node_modules/@angular/cli/models/architect-command.js:46:16)
    at Object.<anonymous> (/zeta/git/ng-multiselect-dropdown/node_modules/@angular/cli/models/command-runner.js:87:23)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

Using `npm i` also fails, here's the relevant part of the log:
```console
$ npm i
...
> node ./bin/ng-update-message.js

================================================================================
The Angular CLI configuration format has been changed, and your existing configuration can
be updated automatically by running the following command:

  ng update @angular/cli
================================================================================

> ng-multiselect-dropdown@0.1.8 prepublish /zeta/git/ng-multiselect-dropdown
> yarn build:prod

yarn run v1.7.0
$ ng build --prod --base-href https://nileshpatel17.github.io/ng-multiselect-dropdown/
Could not find module "@angular-devkit/build-angular" from "/zeta/git/ng-multiselect-dropdown".
Error: Could not find module "@angular-devkit/build-angular" from "/zeta/git/ng-multiselect-dropdown".
    at Object.resolve (/zeta/git/ng-multiselect-dropdown/node_modules/@angular-devkit/core/node/resolve.js:141:11)
    at Observable.rxjs_1.Observable [as _subscribe] (/zeta/git/ng-multiselect-dropdown/node_modules/@angular-devkit/architect/src/architect.js:132:40)
    at Observable._trySubscribe (/zeta/git/ng-multiselect-dropdown/node_modules/@angular-devkit/architect/node_modules/rxjs/internal/Observable.js:43:25)
    at Observable.subscribe (/zeta/git/ng-multiselect-dropdown/node_modules/@angular-devkit/architect/node_modules/rxjs/internal/Observable.js:29:22)
    at DoOperator.call (/zeta/git/ng-multiselect-dropdown/node_modules/@angular/cli/node_modules/rxjs/internal/operators/tap.js:29:23)
    at Observable.subscribe (/zeta/git/ng-multiselect-dropdown/node_modules/@angular-devkit/architect/node_modules/rxjs/internal/Observable.js:24:22)
    at /zeta/git/ng-multiselect-dropdown/node_modules/@angular/cli/node_modules/rxjs/internal/util/subscribeToObservable.js:10:20
    at Object.subscribeToResult (/zeta/git/ng-multiselect-dropdown/node_modules/@angular/cli/node_modules/rxjs/internal/util/subscribeToResult.js:7:45)
    at MergeMapSubscriber._innerSub (/zeta/git/ng-multiselect-dropdown/node_modules/@angular/cli/node_modules/rxjs/internal/operators/mergeMap.js:75:38)
    at MergeMapSubscriber._tryNext (/zeta/git/ng-multiselect-dropdown/node_modules/@angular/cli/node_modules/rxjs/internal/operators/mergeMap.js:72:14)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
...
```

**Comment by tomsaleeba** [comment]
I'm keen to get this working so I'll send a PR to solve this issue.
